# Generated by Django 6.1.1 on 2026-09-26 16:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "password",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "студент",
                "verbose_name_plural": "студенты",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "email"), name="unique_student_name_email"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                (
                    "age",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "experience",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_high_edu", models.BooleanField(default=False)),
                (
                    "password",
                    models.CharField(
                        max_length=128,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "репетитор",
                "verbose_name_plural": "репетиторы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "last_name", "email"),
                        name="unique_tutor_name_lastname_email",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="written_reviews",
                        to="app.student",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="app.tutor",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tutor", "creator"), name="unique_review_per_student"
                    )
                ],
            },
        ),
    ]
