# Generated by Django 6.1.1 on 2026-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutor",
            name="count_review",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tutor",
            name="rating",
            field=models.FloatField(default=0),
        ),
    ]
